---
- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present

- name: Ensure mongod user exists
  user:
    name: mongod
    state: present
    system: yes

- name: Create environment files
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongod
    group: mongod
    mode: '0644'
  notify: Restart MongoDB

- name: Create MongoDB database using shell command
  shell: |
    mongosh --eval 'use dof' --quiet
  register: mongo_output
  changed_when: "'switched to db dof' in mongo_output.stderr"

- name: Verify database creation
  shell: |
    mongosh --eval 'show dbs' --quiet
  register: show_dbs
  changed_when: false

- name: Start and enable MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes