---
- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: Configure MongoDB to listen only on localhost
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongod
    group: mongod
    mode: '0644'
  notify: Restart MongoDB

- name: Start and enable MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes