---
- name: Deploy VueJS Application
  hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
  tasks:
    - collections:
        - community.mongodb
    - name: Install MongoDB collection
      ansible.builtin.ansible_galaxy_collection:
        name: community.mongodb
        state: present
  roles:
    - cleanup
    - mongodb
    - nodejs