cleanup_paths:
  - /tmp/*
  - /var/tmp/*
log_paths:
  - /var/log/*.log
  - /var/log/*.gz
services_to_stop:
  - apache2
  - mongodb
packages_to_remove:
  - nodejs
  - npm
  - apache2
  - mongodb-org
script_path: '/tmp/cleanup.sh'